### ISSUE TITLE
Kor detect secret as Orphan but it's being used

### ISSUE THREAD

**Issue by sosoriov** [yonahd/kor#155]
**Describe the bug**
I have an application that uses a secret as Volume and Kor detected as unused:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: features-ravendbcertificate
  name: features-ravendbcertificate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: features-ravendbcertificate
  template:
    metadata:
      labels:
        app: features-ravendbcertificate
    spec:
      containers:
      - image: features-ravendbcertificate:v1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        name: features-ravendbcertificate
        volumeMounts:
        - mountPath: /etc/certificates
          name: certificates
      volumes:
      - name: certificates
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: features-ravendbcertificate
```

**To Reproduce**
See the app above, and run the kor command:

```
kor secret -n dsp
```

```
+----+----------------------------------------------------------------------+
| #  |                            RESOURCE NAME                             |
+----+----------------------------------------------------------------------+
|  1 | features-ravendbcertificate                             |

```

**Expected behavior**
`features-ravendbcertificate` should not be marked for deletion

**Screenshots**

**OS version, architecture and kor version**
Windows WSL 2
Kor version: v0.2.9
