### ISSUE TITLE
Discuss: resources usage by CRD

### ISSUE THREAD

**Issue by incubator4** [yonahd/kor#21]
First of all I would like to express my great interest in this project.

And I clone this project to use ( casue of have no arm64/darwin yet), but I noticed that there might be some problems.
**KOR** could not find resources used by crd.

For example, I use traefik `ingressroute` for my cluster ingress, and I would use cert signed by cert-manager, which store in kubernetes `secret`, but KOR treats it as orphaned resources.

I don't have a particularly good solution at the moment, so I hope to discuss it in this issue. Adding all CRDs is obviously unrealistic

**Comment by yonahd** [comment]
Regarding arm64/darwin We can add support for that in one of the upcoming releases.

Regarding certificates, if these secrets are used in an ingress we should be detecting them.
@incubator4 Can you share the ingress manifest?

**Comment by incubator4** [comment]
> Regarding arm64/darwin We can add support for that in one of the upcoming releases.
> 
> Regarding certificates, if these secrets are used in an ingress we should be detecting them. @incubator4 Can you share the ingress manifest?

My apologize, maybe I didn't explain clearly. I means that resources usage by crd cound not be detected. May be workload resources could be detected, cause of pods are ultimately required to run workloads, and configmap/secret would be used by pod. 

But  in other case, for example I use traefik for ingress controller and cert-manager to manage cert.

This is a  cert example.
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <some-name>
  namespace: default
spec:
  dnsNames:
  - <some-hostname>
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
  secretName: <secret-would-be-created>
```

And I would use this secret in traefik IngressRoute.This is an example.
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: <some-name>
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`<some-hostname>`)
    services:
    - name: <svc>
      port: 80
tls:
    secretName: <secret-would-be-created>
```
