### ISSUE TITLE
Add roles with no rules to unused roles

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#67]
Example use case:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test
  namespace: test
rules: null
```
